services:
  mysql:
    image: mysql:8.0
    container_name: njs_habsen_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: njs_habsen
      TZ: Asia/Jakarta
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 20

  phpmyadmin:
    image: phpmyadmin:5
    container_name: njs_habsen_pma
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      PMA_HOST: mysql
      PMA_PORT: 33006
    ports:
      - "8081:80"

volumes:
  mysql_data:
